language: node_js   #设置语言
node_js: 13     #设置相应的版本
notifications: #开启邮件通知
  email:
    recipients:
    - mikasatang@gmail.com  
    on_success: always
    on_failure: always
cache:
    directories:
        - node_modules    #据说可以减少travis构建时间
before_install:
  - npm install -g hexo-cli
install:
  - npm install   #安装hexo及插件
  - npm install hexo-deployer-git --save
  - npm install hexo-git-backup --save
script:
  - hexo clean
  - hexo g   #生成
after_script:
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${Travis_CI}/g" ./_config.yml
  # 部署博客相关命令
  - echo "misakatang.cn" > ./public/CNAME
  - cp LICENSE ./public
  - cp README.md ./public
  - git config --global user.name "misakatang"
  - git config --global user.email "mikasatang@gmail.com"
  - hexo deploy
branches:
  only:
  - source  #只监测这个分支，一有动静就开始构建
