language: node_js
install:
    - npm install
script:
    - hexo g
after_script:
    - cd ./public
    - git init
    - git config user.name "misakatang"
    - git config user.email "mikasatang@gmail.com"
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${6abd39233d904d122eeca510edd6d8f0abd3249d}@${GH_REF}" master:master
branches:
    only:
        - backup
env:
    global:
        - GH_REF: github.com/913647909/913647909.github.io.git